#!/usr/bin/env bash
# will display information about subdomains.
# The [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

dom_info() {
	line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 2 ]; then
	dom_info "$1" "$2";
else
	for sub in www lb-01 web-01 web-02; do
		dom_info "$1" "$sub"
	done
fi
