#!/usr/bin/env bash
# Install nginx on your web-01 server and write text messag
apt-get -y update
apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "/listen 80 default_server;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\n    root /var/www/html;\n    internal;\n}" /etc/nginx/sites-available/default
service nginx restart
