#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it
mysqldump --all-databases -u root --password="$1" > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
tar -czvf "$file_name" backup.sql
