#!/usr/bin/env bash
# script Creates the file /var/run/myscript.pid containing its PID
j=0
pid_f="/var/run/myscript.pid"
echo $BASHPID > "$pid_f"
trap 'echo "I hate the kill command"; rm "$pid_f"; exit 0;' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm $pid_f"; exit 0;' SIGQUIT
while [ $j ];
do
	echo 'To infinity and beyond'
	sleep 2
done;

