#!/usr/bin/env bash
# script displays "To infinity and beyond" indefinitely with a sleep interval of 2 seconds
# I am invincible!!! when receiving a SIGTERM signa
trap 'echo "I am invincible!!!"' SIGTERM
while true;
do
  echo "To infinity and beyond"
  sleep 2
done
